version: '2.2'

services:
  server:
    container_name: nikitapavets-ssr
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    ports:
      - '3000:3000'
    restart: always
    command: ['yarn', 'deploy']
